### ISSUE TITLE
Typo:  interajir 

### ISSUE THREAD

**Issue by beothorn** [CommunityBootcamp/Open-Source-Bootcamp#1]
https://github.com/CommunityBootcamp/Open-Source-Bootcamp/blob/master/Conversation/Hands-on%20Lab%20%231%20-%20Web%20App%20Bot%20no%20Azure%2C%20QnA%20Maker.md

Conectar um bot no Skype e interajir com ele por lá

Typo interajir seria interagir

**Comment by cyz** [comment]
fixed, thanks :)
